import { library } from '@fortawesome/fontawesome-svg-core'

import {
    faLink,
    faCircleInfo,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faTimes,
    faArrowUpRightFromSquare,
    faPenToSquare,
    faFloppyDisk,
    faBan,
    faSquarePlus,
    faSquareMinus,
    faAsterisk,
    faTrash,
    faTriangleExclamation,
    faAngleLeft,
    faAngleRight,
    faAngleDown,
    faAngleUp,
    faBars,
    faFileArrowDown,
    faFileArrowUp,
    faArrowRight,
    faBolt,
    faLock,
    faLockOpen,
    faCopy,
    faCircleCheck,
    faCircleXmark,
    faCircleQuestion,
    // Domain icons: fund types, statement states, roles (see SpecialIcons.jsx)
    faWater,
    faCalendarDays,
    faChartLine,
    faFolder,
    faEyeSlash,
    faHourglassHalf,
    faUserShield,
    faBookOpen,
    faKey,
    faEye
} from '@fortawesome/free-solid-svg-icons'

import {
    faCircle,
    faCircleDot
} from '@fortawesome/free-regular-svg-icons'

library.add(
    faLink,
    faCircleInfo,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faTimes,
    faArrowUpRightFromSquare,
    faPenToSquare,
    faFloppyDisk,
    faBan,
    faSquarePlus,
    faSquareMinus,
    faAsterisk,
    faTrash,
    faTriangleExclamation,
    faAngleLeft,
    faAngleRight,
    faAngleDown,
    faAngleUp,
    faBars,
    faFileArrowDown,
    faFileArrowUp,
    faArrowRight,
    faBolt,
    faLock,
    faLockOpen,
    faCopy,
    faCircleCheck,
    faCircleXmark,
    faCircleQuestion,

    faWater,
    faCalendarDays,
    faChartLine,
    faFolder,
    faEyeSlash,
    faHourglassHalf,
    faUserShield,
    faBookOpen,
    faKey,
    faEye,

    faCircle,
    faCircleDot
);
